# Generated by Django 5.0.7 on 2024-07-15 12:49

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dcim", "0187_alter_device_vc_position"),
        ("extras", "0115_convert_dashboard_widgets"),
        ("ipam", "0069_gfk_indexes"),
        ("netbox_sd_access", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FabricSite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("name", models.CharField(max_length=200)),
                ("devices", models.ManyToManyField(blank=True, to="dcim.device")),
                ("ip_prefixes", models.ManyToManyField(to="ipam.prefix")),
                (
                    "location",
                    models.OneToOneField(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="dcim.location"
                    ),
                ),
                ("physical_site", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="dcim.site")),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "ordering": ("name",),
            },
        ),
    ]
