# Generated by Django 5.0.7 on 2024-07-15 15:08

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dcim", "0187_alter_device_vc_position"),
        ("extras", "0115_convert_dashboard_widgets"),
        ("ipam", "0069_gfk_indexes"),
        ("netbox_sd_access", "0002_fabricsite"),
    ]

    operations = [
        migrations.CreateModel(
            name="IPTransit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("name", models.CharField(max_length=200)),
                ("comments", models.TextField(blank=True)),
                (
                    "asn",
                    models.OneToOneField(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="ipam.asn"
                    ),
                ),
                (
                    "fabric_site",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="netbox_sd_access.fabricsite",
                    ),
                ),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "IP Transit",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="SDATransit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("name", models.CharField(max_length=200)),
                ("transit_type", models.CharField(default="LISP", max_length=8)),
                (
                    "control_plane_node",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transit_control_nodes",
                        to="dcim.device",
                    ),
                ),
                ("devices", models.ManyToManyField(blank=True, related_name="transit_devices", to="dcim.device")),
                (
                    "fabric_site",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="netbox_sd_access.fabricsite",
                    ),
                ),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "SDA Transit",
                "ordering": ("name",),
            },
        ),
    ]
