# Generated by Django 5.0.7 on 2024-07-16 18:42

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dcim", "0187_alter_device_vc_position"),
        ("extras", "0115_convert_dashboard_widgets"),
        ("netbox_sd_access", "0002_fabricsite"),
    ]

    operations = [
        migrations.CreateModel(
            name="SDADeviceRole",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("role", models.CharField(max_length=50)),
                ("device", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="dcim.device")),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "Device Role",
                "verbose_name_plural": "Device Roles",
                "ordering": ("id",),
            },
        ),
    ]
