# Generated by Django 5.0.7 on 2024-07-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_sd_access", "0003_iptransit_sdatransit"),
    ]

    operations = [
        migrations.AddField(
            model_name="sdatransit",
            name="comments",
            field=models.TextField(blank=True),
        ),
    ]
