# Generated by Django 5.0.7 on 2024-07-16 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dcim", "0187_alter_device_vc_position"),
        ("netbox_sd_access", "0003_remove_fabricsite_devices_sdadevice"),
    ]

    operations = [
        migrations.AddField(
            model_name="sdadevice",
            name="comments",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="sdadevice",
            name="device",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="sda_info", to="dcim.device"
            ),
        ),
    ]
