# Generated by Django 5.0.7 on 2024-07-18 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_sd_access", "0004_alter_fabricsite_ip_prefixes"),
        ("netbox_sd_access", "0004_sdadevice_comments_alter_sdadevice_device"),
    ]

    operations = []
