# Generated by Django 5.0.7 on 2024-07-19 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_sd_access", "0004_sdatransit_comments"),
        ("netbox_sd_access", "0005_merge_20240718_1903"),
    ]

    operations = []
