# Generated by Django 5.0.7 on 2024-07-19 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_sd_access", "0007_alter_sdatransit_devices_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sdatransit",
            name="control_plane_node",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transit_control_nodes",
                to="netbox_sd_access.sdadevice",
            ),
        ),
    ]
