# Generated by Django 5.0.7 on 2024-07-22 18:57

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0115_convert_dashboard_widgets"),
        ("ipam", "0069_gfk_indexes"),
        ("netbox_sd_access", "0008_alter_sdatransit_control_plane_node"),
    ]

    operations = [
        migrations.CreateModel(
            name="VirtualNetwork",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("name", models.CharField(default="Virtual Network", max_length=200)),
                (
                    "fabric_site",
                    models.ManyToManyField(
                        blank=True, related_name="virtual_networks", to="netbox_sd_access.fabricsite"
                    ),
                ),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
                ("vrf", models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to="ipam.vrf")),
            ],
            options={
                "ordering": ("name",),
            },
        ),
    ]
