# Generated by Django 5.0.7 on 2024-07-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dcim", "0187_alter_device_vc_position"),
        ("extras", "0115_convert_dashboard_widgets"),
        ("ipam", "0069_gfk_indexes"),
        ("netbox_sd_access", "0010_alter_virtualnetwork_vrf"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="fabricsite",
            constraint=models.UniqueConstraint(fields=("name",), name="netbox_sd_access_fabric_site_unique_name"),
        ),
        migrations.AddConstraint(
            model_name="ippool",
            constraint=models.UniqueConstraint(fields=("name",), name="netbox_sd_access_ip_pool_unique_name"),
        ),
        migrations.AddConstraint(
            model_name="virtualnetwork",
            constraint=models.UniqueConstraint(fields=("name",), name="netbox_sd_access_vns_unique_name"),
        ),
    ]
