# Generated by Django 5.0.7 on 2024-07-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_sd_access", "0011_fabricsite_netbox_sd_access_fabric_site_unique_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fabricsite",
            name="comments",
            field=models.TextField(blank=True),
        ),
    ]
