# Generated by Django 5.0.7 on 2024-07-29 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_sd_access", "0013_ippool_comments"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SDAccess",
        ),
    ]
